name: Push resume files to S3

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your region

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync --follow-symlinks --delete build s3://yalla-cloud-site --exclude '.git/*' --exclude '.DS_Store' --exclude '.vscode/*' --exclude '.github/' --exclude 'README.md'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution: arn:aws:cloudfront::396913715305:distribution/E3RS5Z5VHDGPM1
          paths: |
            /index.html
            /style.css